#======================================================================
# Project settings
#======================================================================
# Only build master.
branches:
  only:
      - master

language: fortran

#======================================================================
# Environment
#======================================================================
# Use new Travis infrastructure.
sudo: false

# Use a newer Ubuntu
dist: trusty

# Code is Fortran. While docs need doxygen and graphviz to build
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - gcc-6
      - gfortran-6
      - g++-6
      - doxygen
      - graphviz

#======================================================================
# Build Matrix
#======================================================================
matrix:
   include:
#     - os: linux
#       compiler: gcc
     - os: osx
       compiler: gcc

#======================================================================
# Building
#======================================================================
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then brew install gcc6 ; fi

before_script:
  - export CC="gcc-6" FC="gfortran-6" CXX="g++-6" ;

script:
  - mkdir build && cd build && cmake .. && make

#======================================================================
# Notifications
#======================================================================
notifications:
  email:
    recipients: Timothy.P.Brown@noaa.gov
    on_success: change
    on_failure: always
