name: CI test to run CCPP-framework unit tests.

on: [push, pull_request, workflow_dispatch]

jobs:
  build-linux:

    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        py-version: [3.0.1, 3.1.4, 3.2.5, 3.3.5, 3.4.0, 3.4.10, 3.6.0, 3.5.10, 3.6.0, 3.6.15, 3.7.0, 3.7.17, 3.8.0, 3.8.17, 3.9.0, 3.9.16, 3.10.0, 3.10.12, 3.11.0, 3.11.4, 3.12.0-beta.4]
        test-files: [test_metadata_scheme_file.py, test_metadata_table.py, test_var_transforms.py]

    # Environmental variables
    env:
      WRK_ROOT: ${{ github.workspace }}

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{matrix.py-version}}

    - name: Update system packages
      run: sudo apt-get update

    - name: Run unit tests
      run: |
        cd ${WRK_ROOT}/test/unit_tests
        ./${{matrix.test-files}}
